development:
  adapter: postgresql
  encoding: unicode
  database: sports_spike_development
  host: localhost
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: sports_spike_test
  host: localhost
  pool: 5
  username: 
  password: 
